### ISSUE TITLE
Question about datatrain

### ISSUE THREAD

**Issue by Carla-33** [sanchit199617/Naive-Bayes-Classifier#1]
Hi

I have some questions for your system:
1- What program do you use?
2- What operating system do you use?
3- how can I make a dataset? Is it the same datatrain file?
3- What is the difference between C++ and CPP?

Thank you

**Comment by sanchitsgupta** [comment]
Hi @Carla-33 ,

Thank you for your interest in this project.

1. By program if you mean the compiler, then I use GNU c++ compiler (g++). If you are on Ubuntu, then you can install it using `sudo apt install build-essential`.
2. Ubuntu 20.04, but the program should work fine on any Linux-based OS.
3. Yes, [datatrain](https://github.com/sanchitsgupta/naive-bayes-classifier/tree/master/datatrain) directory contains the files used in training. [facedatatrain.txt](https://github.com/sanchitsgupta/naive-bayes-classifier/blob/master/datatrain/facedatatrain.txt) contains the ascii-faces, and [facedatatrainlabels.txt](https://github.com/sanchitsgupta/naive-bayes-classifier/blob/master/datatrain/facedatatrainlabels.txt) contains the labels (`1` is for face and `0` is for non-face).
4. They are the same. C++ source code files have `.cpp` extension.

Let me know if you have any other questions.
